### ISSUE TITLE
CI failure:  Using cmake syntax introduced in 2.8.12

### ISSUE THREAD

**Issue by hjmjohnson** [wjakob/tbb#25]
https://travis-ci.org/wjakob/tbb/jobs/163667285

The syntax you are using for target_link_libraries is only valid in 2.8.12 or greater.

see:
https://cmake.org/cmake/help/v2.8.11/cmake.html
vs:
https://cmake.org/cmake/help/v2.8.12/cmake.html

see note at: https://github.com/wjakob/tbb/commit/b3078a43c25b10ef3fbf5ee90a6de6f96bc47365#diff-af3b638bc2a3e6c650974192a53c7291R218

**Comment by wjakob** [comment]
Fixed, thank you.
