### ISSUE TITLE
Enable debug for Linux/Mac OSX

### ISSUE THREAD

**Issue by rickyzhang82** [wjakob/tbb#27]
I skim through CMakeLists.txt. I don't see it handle CMAKE_BUILD_TYPE=Debug

**Comment by wjakob** [comment]
This happens automatically by CMake, which specifies a different set of flags in this case.

**Comment by rickyzhang82** [comment]
What flags? When I use -DCMAKE_BUILD_TYPE=Debug, I don't see debug library is generated. The binary package from Intel will have post fix _debug attach to compiled library.
