### ISSUE TITLE
Linker looks for tbb.lib and tbb_debug.lib instead of tbb_static.lib on MSVC builds

### ISSUE THREAD

**Issue by ysaw** [wjakob/tbb#29]
When including the `tbb_static` library on MSVC builds:
```
target_link_libraries (our_target
    PUBLIC our_target_other
    PRIVATE our_target_internal tbb_static
)
```

`our_target` fails to build with these errors, depending on the build type (release or debug):
```LINK : fatal error LNK1104: cannot open file 'tbb.lib'```
```LINK : fatal error LNK1104: cannot open file 'tbb_debug.lib'```

these were the lines that seem to cause the build error:
https://github.com/wjakob/tbb/blob/master/include/tbb/internal/_tbb_windef.h#L61-L73

The error went away after we added `__TBB_NO_IMPLICIT_LINKAGE=1` to the compile definitions for tbb by adding this `target_compile_definitions` line here in the tbb cmake file:
```
if (TBB_BUILD_STATIC)
  add_library(tbb_static STATIC ${tbb_src})
  set_property(TARGET tbb_static APPEND PROPERTY COMPILE_DEFINITIONS "__TBB_BUILD=1")
  set_property(TARGET tbb_static APPEND_STRING PROPERTY COMPILE_FLAGS ${ENABLE_RTTI})
  install(TARGETS tbb_static ARCHIVE DESTINATION lib)

  target_compile_definitions(tbb_static PUBLIC __TBB_NO_IMPLICIT_LINKAGE=1)
...
```

Is this the correct solution to the problem we're seeing?

**Comment by wjakob** [comment]
That sounds like a great solution. I will add these to CMakeLists.txt.
