### ISSUE TITLE
Configure date and version string.

### ISSUE THREAD

**Issue by jdumas** [wjakob/tbb#47]
Hi,

Right now everytime one reruns CMake, tbb's `CMakeLists.txt` will call [`date`](https://github.com/wjakob/tbb/blob/4c3ffe5a5f37addef0dd6283c74c4402a3b4ebc9/CMakeLists.txt#L357) and generate a new `version_string.ver`, forcing tbb and all its dependents to be linked again. Can I suggest that we execute the `date` command only if the a certain cached variable has not been set (i.e. on the first run of the CMake). Even so I'd also rather have the option to set it to `Unkown` by default and be done with it, since it would allow programs like `ccache` to take advantage of it in case the `CMakeCache.txt` of a project is deleted (i.e. you don't have to link again since it's cached by `ccache` -- but that only works if the `date` doesn't appear in the version string).

**Comment by wjakob** [comment]
This seems reasonable -- can you create a PR with this change?

**Comment by jdumas** [comment]
Sure, will do that tomorrow.
