### ISSUE TITLE
No TBBConfig.cmake generated(?)

### ISSUE THREAD

**Issue by kabcode** [wjakob/tbb#52]
Hi,

i am trying to build this repository to include the build into another cmake project. My environment is Windows with Visual Studio 2015 (vc14,x64), CMake (3.11.1, using cmake-gui).
 My approach was to define the source and build directory and configure and generate the project using the CMakeLists.txt (LIBRT and LIDL are not available). Open the generated solution file VS2015. Build ALL_BUILD in Debug mode.

I can build this repo but for further use I do not find any TBBConfig.cmake file. There is no file generated in the build tree. Should there be a config.cmake file?

**Comment by mitjap** [comment]
If you need this I have it on my master branch here: https://github.com/mitjap/tbb/

You define CMKAE_INSTALL_PREFIX as you normally would and it also installs tbbConfig.cmake.
When using `tbb` in your project you use `find_package(tbb REQUIRED)` and set `tbb_DIR`.

**Comment by jschueller** [comment]
this can be closed
