### ISSUE TITLE
Integrate local TBB and FindTBB.cmake

### ISSUE THREAD

**Issue by weidenka** [wjakob/tbb#53]
My project depends on ParallelSTL which in turn requires TBB. I want to use the local TBB version only of none is available. ParallelSTL expects the target `TBB::tbb` unfortunatly, TBB's target is `tbb`. After fixing this with an alias I obtian the error message:
``` 
CMake Error in ThirdParty/parallelstl/CMakeLists.txt:
  export called with target "ParallelSTL" which requires target "tbb" that is
  not in the export set. 
```
Probably someone else finds my solution helpful:
```
# Try to find system TBB
find_package( TBB 2018 )
if(NOT TBB_FOUND)
  add_subdirectory(wjakob-tbb)
  set(TBB_FOUND ON)
  add_library(TBB::tbb ALIAS tbb)
  add_library(TBB::tbbmalloc ALIAS tbbmalloc)
  add_library(TBB::tbbmalloc_proxy ALIAS tbbmalloc_proxy)
  export(TARGETS tbb tbbmalloc tbbmalloc_proxy NAMESPACE TBB:: FILE TBBTargets.cmake)
  export(PACKAGE TBB)
endif()

# add_subdirectory(parallelstl)
````
A `FindTBB.cmake` like [this](https://github.com/justusc/FindTBB) one is required.

Anyway the reason for this issue is that it would be nice if your build system could export its targets. Let me know if you are interested in a pull request (since a similar one is pending I wasn't sure about that).

**Comment by jschueller** [comment]
We have a TBB:: namespace now so this should work, this can be closed
