### ISSUE TITLE
Is there a plan for adding TBBconfig.cmake?

### ISSUE THREAD

**Issue by Nekto89** [wjakob/tbb#55]
TBBConfig.cmake is needed for finding TBB package through "find_package". Other libraries (for example, ITK) use this method for integrating TBB into their build.

**Comment by qis** [comment]
Yeah, proper exports instead of a script hack would be nice.

**Comment by jschueller** [comment]
this can be closed

**Comment by qis** [comment]
@jschueller Thank you very much!

**Comment by qis** [comment]
@wjakob I don't see the exports in CMakeLists.txt. Did I miss it, or was this issue wrongly closed?

**Comment by jschueller** [comment]
look for "EXPORT TBB"

**Comment by qis** [comment]
@jschueller Yes, but it's only installed for shared libraries: https://github.com/wjakob/tbb/blob/ddbe45cd3ad89df9a84cd77013d5898fc48b8e89/CMakeLists.txt#L376-L378
