### ISSUE TITLE
Question about static libraries

### ISSUE THREAD

**Issue by leonsal** [wjakob/tbb#58]
Hi,

Your CMakeLists.txt can generate static libraries which is very good but I read
some comments that using ```tbb``` as a static library can be problematic:

[static linking tbb](https://software.intel.com/en-us/forums/intel-threading-building-blocks/topic/565029)

Do you have any experience on issues in linking an application statically with tbb ?
Regards.

**Comment by wjakob** [comment]
It's fine to do this as long as you don't  link to other software that *also* include their own version of TBB.
