### ISSUE TITLE
unsupported option '/volatile:iso'

### ISSUE THREAD

**Issue by jschueller** [wjakob/tbb#9]
With vc 2008,2010 and 2015 I get a ton of:
```
cl : Command line warning D9002 : ignoring unknown option '/volatile:iso'
```
more details at https://ci.appveyor.com/project/conda-forge/tbb-feedstock/branch/master

However this seems correct according to ms doc, any clue ?

**Comment by wjakob** [comment]
not sure, it seems valid (http://graphics.stanford.edu/courses/cs205a-15-spring/). Note that 2008 and 2010 are not supported here.

**Comment by jschueller** [comment]
@wjakob note that it builds well on 2008 & 2010
